#ifndef     _TYPES_H_
#define     _TYPES_H_

// standard includes
#include    <cstring>
#include    <cmath>
#include    <cstdlib>
#include    <cstdio>
#include    <iostream>
#include    <iomanip>
#include    <sstream>
#include    <vector>
#include    <set>
#include    <map>
using namespace std;

// a few basic types
typedef unsigned char byte;
typedef unsigned short ushort;
typedef unsigned int uint;
typedef unsigned long ulong;

// this is primarily for testing purposes
#ifndef     TEST_ASSERTION
#define     TEST_ASSERTION(x)
#endif  //  TEST_ASSERTION

#endif // _TYPES_H_
